### PR TITLE
Request SMTP.Send permission

### PR DESCRIPTION
**Pull request by timo0**
We running currently in an issue and we have strong hopes that this will resolve that.

With the current permissions we can view the inbox but SMTP is not working

### CODE REVIEW

**Comment by j-dimension** [comment]
Could also be a missing privilege in the app that was set up. 

Do you have an error message or stack trace?

**Comment by j-dimension** [comment]
@timo0  I built a client but failed to upload it due to limited bandwidth here. Is next week sufficient? Otherwise I'll have to find a spot here that has a better uplink.

**Comment by timo0** [comment]
@j-dimension we found a workaround but still curious if this would had helped - but next week is engough

**Comment by j-dimension** [comment]
@timo0 do you have the latest 2.4 preview installed in a test env? If so, the easiest way is to use those client installers (https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2F2023-07-26_2.4.0%2FClient) and then drop the single .jar file from that same share to the clients installation folder. This contains the change of this pull request. 

Also, can you share some details about the workaround? Could be something worth documenting for others. Thanks!

**Comment by timo0** [comment]
We can send this on pause - we will have a post mortem meeting after all vacations and we can share the results afterwards

**Pull request closed without merging**
